# .github/release.yml

changelog:
  exclude:
    labels:
    - wontfi
    authors:
    - tkopecky
  categories:
    - title: Breaking Changes 🛠
      labels:
        - wontfix
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: Other Changes
      labels:
        - *
